# nombre del pipeline
name: GH-build-DEV

# eventos disparadores 
on:
  push:
    branches: [ "main" ] # eventos disparadores en branch main

jobs:
  build:

    runs-on: ubuntu-24.04 # siempre explicitar la version del Sistema Operativo

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: | # 8.0.x son versiones LTS
            8.0.x  
            9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Read Secrets
      run: echo ${{ secrets.USUARIO }}
    - name: Send email
      uses: dawidd6/action-send-mail@v6
      with:
              server_address: ${{ secrets.SMTP_HOST}}
              server_port: ${{ secrets.SMTP_PORT}}
              username: ${{ secrets.SMTP_USER }}
              password: ${{ secrets.SMTP_PASS }}
              subject: "Pipeline de PRUEBA - GH-build-DEV"
              to: muniz.gonzalo1@gmail.com
              from: ${{ secrets.SMTP_USER }}
              content_type: text/plain
              body: "El pipeline de CI se ejecuto correctamente!!"
